mysqldb:
  image: mysql:latest
  environment:
    MYSQL_DATABASE: sample
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: supersecret

mywildfly:
  image: fstn/wildfly-mysql-user-service
  links:
    - mysqldb:db
  ports:
    - 8080:8080
  volumes:
    - /home/sza/DockerVolume/restContent:/opt/jboss/wildfly/standalone/deployments/:rw

myweb:
  image: fstn/nginxrest
  links:
    - mywildfly:ws
  ports:
    - 80:80
  volumes:
    - /home/sza/DockerVolume/webContent:/usr/share/nginx/html:ro
